version: '3'

services:
  app:
    build: ./app
    container_name: app_container
    ports:
      - "5000:5000"
    volumes:
      - ./db:/data
    networks:
      - my_network

  parser:
    build: ./parser
    container_name: parser_container
    ports:
      - "5001:5000"
    volumes:
      - ./db:/data
    networks:
      - my_network

  db:
    build: ./db
    container_name: db_container
    volumes:
      - ./db:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
